first_project/first_app/urls.py
from django.urls import path
from first_app import views

#Template Tagging
app_name = 'first_app'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/', views.other,name='other'),
    path('table_access_records/',views.table_access_records,name='table_access_records'),
    path('home/',views.home,name='home'),
    path('form_name/',views.form_name_view,name='form_name'),
    path('store_details/',views.store_details,name='store_details'),
    path('signup/',views.signup,name='signup')
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('',views.index,name="index"),
    # path('topics/', include('topics.urls')),
    path('admin/', admin.site.urls),
    path('first_app/',include('first_app.urls'))
]

first_project/topics/urls.py
from django.urls import path
from topics import views


urlpatterns = [
    path('', views.index,name='topics_index')
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=255,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class User(models.Model):
    first_name = models.CharField(max_length=264, unique=True)
    last_name = models.CharField(max_length=264,unique=True)
    email = models.EmailField()

    def __str__(self):
        return self.first_name

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional class
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.UserName

first_project/topics/models.py
from django.db import models

class Topic(models.Model):
    top_name = models.CharField(max_length = 265, unique=True)

    def __str__(self):
        return self.top_name
# topic,name, url
class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=265,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name
# name,date
class AccessRecord(models.Mode):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first_project/first_app/forms.py
from django import forms
from first_app.models import User,UserProfileInfo
from django.contrib.auth.models import User
from django.core import validators

#----CUSTOM VALIDATOR------------
def check_for_z(value):
    if value[0].lower() != 'v':
        raise forms.ValidationError('Name Need to Start with Z')

class FormName(forms.Form):
    name = forms.CharField(validators = [check_for_z]) #Application of Custom validator check_for_z
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter you email again")
    text = forms.CharField(widget = forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
                                validators = [validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("Email is not match!")

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError('Bot Found')
    #     return botcatcher

class StoreDetails(forms.Form):
    name = forms.CharField()
    code = forms.CharField()
    area = forms.IntegerField()
    location = forms.CharField(widget = forms.Textarea)

class NewUserForm(forms.ModelForm):
    # If Needed Validator will be in HERE
      # first_name = forms.CharField(validator=[])
    class Meta():
        model = User
        fields = '__all__' #Get All Fields in the Model

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from first_app.models import Topic,Webpage,AccessRecord
from first_app import forms
from first_app.forms import NewUserForm
# Create your views here.

# def index(request):
#     webpages_list = AccessRecord.objects.order_by('date')
#     date_dict = {'access_records':webpages_list}
#     return render(request,'first_app/index.html',context=date_dict)

def index(request):
    content = {'name':'Hello World'}
    return render(request,'first_app/index.html',context=content)

def other(request):
    return render(request, 'first_app/other.html')

def relative(request):
    return render (request,'first_app/relative_url_templates.html')

def table_access_records(request):
    webpages_list = AccessRecord.objects.order_by('date')
    table_content = {'access_records':webpages_list}
    return render(request,'first_app/table.html',context=table_content)

def home(request):
    return  render(request,'first_app/home.html')

def form_name_view(request):
    form = forms.FormName()

    if request.method =='POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            #DO SOMETHING CODE
            print("VALIDATION SUCCESS")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])

    content = {'form':form}
    return  render(request,'first_app/form_page.html',context=content)


def store_details(request):
    form = forms.StoreDetails()

    if request.method == 'POST':
        form = forms.StoreDetails(request.POST)

        if form.is_valid():
            #CODE HERE

            print("VALIDATION SUCCESS")
            print('STORE NAME: '+form.cleaned_data['name'])
            print('STORE CODE: '+form.cleaned_data['code'])
            print('LOCATION: '+form.cleaned_data['location'])

    content = {'form_store':form}
    return render(request, 'first_app/new_store.html',context = content)

def signup(request):
    form = NewUserForm()
    if request.method == 'POST':
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Error From Invalid')
    form_content = {'form':form}
    return render(request,'first_app/signup.html',context=form_content)

first_project/topics/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    index_topics = {"content":"This is the content of the Topic Page"}
    return render(request,'topics/index.html',context=index_topics)

first_project/templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base HTML</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
        <div class="container">
          <ul class='nav navbar-nav'>
            <li ><a class='navbar-brand' href="{% url 'index' %}">BRAND</a></li>
            <li ><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
            <li ><a class='navbar-link' href="{% url 'first_app:other' %}">Other</a></li>
            <li><a class='navbar-link' href="{% url 'first_app:table_access_records' %}">Table</a></li>
            <li><a class='navbar-link' href="{% url 'first_app:form_name' %}">Form</a></li>
            <li><a class="navbar-link" href="{% url 'first_app:store_details' %}">Store </a></li>
            <li><a class="navbar-link" href="{% url 'first_app:signup'%}">Sign Up</a> </li>
          </ul>
        </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited once extend -->
      {% endblock %}
    </div>
  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
  {% block body_block %}
    <div class="container">
      <h1>New Name</h1>
      <form  method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class='btn btn-primary' value="submit">
      </form>
    </div>
  {% endblock %}
  </body>
</html>

first_project/templates/first_app/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>
    <h1>Welcome to Home Page</h1>
    <h2> Go to Form Page to fill up the form </h2>

  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
  {% extends 'first_app/base.html' %}
    {% block body_block %}
      <h1>Welcome to Index</h1>
      <h2>This is the index page html showing</h2>
      {{name|cut:'Hello'}}  <!--- Remove 'Hello' in Hello World --->
    {% endblock %}

first_project/templates/first_app/new_store.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block body_block %}
  <h1>New Store</h1>
  <div class="container">
    <form method="post">
      {{form_store.as_p}}
      {% csrf_token %}

      <input type="submit" class='btn btn-success' value="submit">
    </form>
  </div>
{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>

{% extends 'first_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is a sample of template Inheritance</h2>
  {% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RELATIVE</title>
  </head>
  <body>
    <h1>Welcome to Relative Url Templates</h1>
    <a href="{% url 'index'  %}">Index</a>
    <a href="{% url 'first_app:other'  %}">Other Page</a>
    <a href="{% url 'first_app:relative'  %}">Relative</a>
  </body>
</html>

first_project/templates/first_app/signup.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block body_block %}
        <h1>Welcome!</h1>
        <h2>Sign Up</h2>

        <form method="post">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" value="Submit">
        </form>
{% endblock %}

first_project/templates/first_app/table.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
  {% block body_block %}
    <h1>This is the Access Record Table</h1>
    <div class="table">
      {% if access_records %}
          <table>
            <thead>
              <th>Site Name</th>
              <th>Date Access</th>
            </thead>
            <tbody>
                {% for acc in access_records %}
                  <tr>
                    <td>{{acc.name}}</td>
                    <td>{{acc.date}}</td>
                  </tr>
                {% endfor %}
            </tbody>
          </table>
      {% else %}
        <p>No Access Record Found</p>
      {% endif %}
    </div>

  {% endblock %}

first_project/templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>First App Index</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  </head>
  <body>

    <h1>My Table</h1>
    <div class="table">
        {% if access_records %}
          <table>
            <thead>
              <th>Site Name</th>
              <th>Date Accessed</th>
            </thead>

            <tbody>
              {% for acc in access_records %}
              <tr>
                <td>{{acc.name}}</td>
                <td>{{acc.date}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>NO ACCESS RECORD FOUND</p>
        {% endif %}
    </div>

  </body>
</html>

first_project/templates/topics/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Topics</title>
  </head>
  <body>
      <h1>This is the Topics</h1>
      {{ content }}
  </body>
</html>