auth_user/auth_user/urls.py
from django.contrib import admin
from django.urls import path,include
from auth_user_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('auth_user_app/',include('auth_user_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

auth_user/auth_user_app/urls.py
from django.urls import path
from auth_user_app import views

app_name = 'auth_user_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='login')
]

auth_user/auth_user_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pics = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

auth_user/auth_user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from auth_user_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('email','username','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields= ('portfolio_site','profile_pics')

auth_user/auth_user_app/views.py
from django.shortcuts import render
from auth_user_app.forms import UserForm,UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.
def index(request):
    return render(request,'index.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            # Link extra fields in user model  in view
            profile.user = user

            if 'profile_pics' in request.FILES:
                profile.profile_pics = request.FILES['profile_pics']
                profile.save()
                registered =True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    content = {'user_form':user_form,'profile_form':profile_form,'registered':registered}
    return render(request,'auth_user_app/registration.html',context =content)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account is not active')
        else:
            print('Some tried to Login and Failed')
            print('Username :{}  and password {}'.format(username,password))
            return HttpResponse("Invalid Deatils Supplies")

    else:
        return render(request, 'auth_user_app/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Your area Logged In")

auth_user/templates/auth_user_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
  </head>
  <body>
      <nav class='navbar navbar-default navbard-static-top'>
          <div class="container">
            <ul class='nav navbar-nav'>
                <li><a class='navbar-brand' href="{% url 'index' %}">DJANGO</a></li>
                <li><a class='navbar-link'href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class='navbar-link'href="{% url 'auth_user_app:register' %}">REGISTER</a></li>

                {% if user.is_authenticated %}
                <li> <a class='navbar-link' href="{% url 'logout' %}">Logout</a> </li>
                {% else %}
                <li><a class='navbar-link' href="{% url 'auth_user_app:login' %}">Login</a></li>
                {% endif %}

            </ul>
          </div>
      </nav>

      <div class="container">
        {% block body_block %}

        {% endblock %}
      </div>
  </body>
</html>

auth_user/templates/auth_user_app/login.html
{% extends 'auth_user_app/base.html' %}

{% block body_block %}
  <h1> Please Login </h1>
  <form action="{% url 'auth_user_app:login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password: </label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">
  </form>

{% endblock %}

auth_user/templates/auth_user_app/registration.html
{% extends 'auth_user_app/base.html' %}

{% load static %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for Registering</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h2>Fill out the form</h2>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" value="Register">
    </form>
  {% endif %}
</div>

{% endblock %}

auth_user/templates/index.html
{% extends 'auth_user_app/base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome!</h1>
  </div>
{% endblock %}